const DESCRIPTION_LIMIT = 140;
const FILM_COUNT = 15;
const FILM_COUNT_PER_STEP = 5;
const TOP_RATED_FILM_COUNT = 2;
const MOST_COMMENTED_FILM_COUNT = 2;


export { DESCRIPTION_LIMIT, FILM_COUNT, FILM_COUNT_PER_STEP, TOP_RATED_FILM_COUNT, MOST_COMMENTED_FILM_COUNT };
