const DESCRIPTION_LIMIT = 140;
const FILM_COUNT = 22;
const FILM_COUNT_PER_STEP = 5;
const TOP_RATED_FILM_COUNT = 2;
const MOST_COMMENTED_FILM_COUNT = 2;
const FILM_CARD_ACTIVE_CONTROL_BUTTON_CLASS = 'film-card__controls-item--active';
const POPUP_ACTIVE_CONTROL_BUTTON_CLASS = 'film-details__control-button--active';
const PopupModes = {
  CLOSED: 'closed',
  OPENED: 'opened',
};

export { DESCRIPTION_LIMIT,
  FILM_COUNT,
  FILM_COUNT_PER_STEP,
  TOP_RATED_FILM_COUNT,
  MOST_COMMENTED_FILM_COUNT,
  POPUP_ACTIVE_CONTROL_BUTTON_CLASS,
  FILM_CARD_ACTIVE_CONTROL_BUTTON_CLASS,
  PopupModes };
